Motor:

	teeth = 20

	profile = 3

Mechanizem:

	teeth = 40

	profile = 3